site_name: Rohit Gupta - Technical Writer Portfolio
site_url: https://rcg1412.github.io/Portfolio/
repo_url: https://github.com/RCG1412/Portfolio.git
repo_name: Portfolio

docs_dir: .
site_dir: site
use_directory_urls: true
strict: true

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: blue
    - scheme: slate
      primary: indigo
      accent: blue

nav:
  - Home: README.md
  - API Docs:
      - Sample API: api-docs/sample-api.md
  - Product Docs:
      - Getting Started: product-docs/getting-started.md

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg